print ("Dindin Pastrana de Belen")
print ("Bahi, Gasan, Marinduque")
print ("June 28, 2000")
print ("Marinduque State College")
print ("Bachelor of Science in Information Technology")
print ("2")
print ("A")
print ("Reading books")
print ("Watching anime")
print ("Watching KDramas")
print ("Crocheting")
print ("Sketching manga characters")
print ("Digital painting")